// translation-qa workflow: (optionally TRANSLATE to Ukrainian) -> analyze -> apply -> re-analyze,
// until the analyzer reports nothing to fix TWICE in a row (two-strike «Ні») or a safety cap is hit.
// NO oscillation / flip-flop / hashing (by design — Opus is trusted to converge; extra cycles OK).
//
// Subagents are invoked BY agentType. The production prompts (translate.md / analyzer.md / editor.md)
// are baked into project agent definitions (.claude/agents/translation-{translator,analyzer,editor}
// [-science].md) as their SYSTEM prompts (generated by generate-agents.mjs). The science variant is
// chosen via isScience; the per-article date is supplied in the user message (can't bake a dynamic
// date into a static agent).
//
// Translation runs FIRST only when the article is not Ukrainian yet (language != 'uk' && !isTranslated,
// or an explicit translate:true) — mirroring prod, where TranslateNewsJob (Gemini) runs upstream of
// the analyze↔apply loop. Here the translator is a Claude agent carrying translate.md.
//
// `args` arrives from the Workflow tool as a JSON STRING in this runtime -> parse defensively.
// Authored using only documented Workflow constructs.
//
// ───────────────────────────────────────────────────────────────────────────────────────────────────
// HOW THE translation-qa SKILL DRIVES THIS, AND WHY. Rationale lives HERE (an executed file — node ignores
// comments) so the orchestrator does NOT re-read it every run; SKILL.md stays a lean command list.
//
// Flow of `/translation-qa <id>`:
//   1. haiku `translation-fetcher` runs fetch-api.mjs       -> GET  /news/{id}/translation -> source.json
//   2. orchestrator runs bake-workflow.mjs                  -> inlines the article into a copy of THIS file
//   3. orchestrator runs Workflow({scriptPath: run.mjs})    -> THIS loop (translate? -> analyze<->apply)
//   4. haiku `translation-poster` runs post-api.mjs --apply -> POST /news/{id}/translation (autonomous)
//   5. orchestrator reports the verdict. Opus never sees the article body.
//
// Why it is shaped this way:
//   - Body never through an AI: the ~58 KB article moves file->curl->API both ways (fetch-api writes the GET
//     body to a file; post-api streams it to curl via stdin). LLMs corrupt long text, so only node/curl touch
//     the bytes — which is also WHY the I/O is two haiku agents running helpers, not the Opus orchestrator.
//   - Server-side PHP does ALL verification (bearer auth; optimistic md5 lock -> 409; UTF-8 + C0 strip; 64 KB
//     BYTE cap; flags is_translated/is_deep/is_deepest=1,is_auto=0; cycles->analysis_count). Agents verify nothing.
//   - The write is AUTONOMOUS (no human gate). The optimistic md5 lock (publish_content unchanged since the read)
//     is the safety net; a non-converged ('capped') run is REFUSED by post-api.mjs unless --force.
//   - analyzer + translator run at effort:max (their .claude/agents frontmatter); the Sonnet editor does not
//     (Sonnet has no xhigh/max). agent() has NO effort option -> frontmatter is the only per-agent knob.
//   - Scope: the orchestrator does ONLY fetch->bake->run->post->report. It must NOT audit article state
//     (language=en + is_translated=false is a NORMAL untranslated-review-queue input), read the body, or explore
//     the codebase. The linguistic subagents may spend unlimited tokens for quality.
//   - Prompts are baked into .claude/agents/translation-* by generate-agents.mjs (re-run + restart CC when
//     resources/prompts/{translate,analyzer,editor}.md change). The old SSH-tinker read + writeback.mjs are superseded.
// ───────────────────────────────────────────────────────────────────────────────────────────────────

export const meta = {
  name: 'translation-qa',
  description: 'Optionally translate a source article to Ukrainian, then loop analyzer + editor subagents (invoked by agentType; prod prompts as system prompts) until the analyzer returns two consecutive «Ні». No oscillation tracking.',
  phases: [
    { title: 'Translate', detail: 'translation-translator agent translates the article to Ukrainian (only if not already Ukrainian)' },
    { title: 'Analyze', detail: 'translation-analyzer agent returns verdict + corrections' },
    { title: 'Apply', detail: 'translation-editor agent applies the corrections' },
  ],
};

// Analyzer returns verdict + the full corrections text (empty when "Ні").
const ANALYZER_SCHEMA = {
  type: 'object',
  required: ['verdict'],
  properties: {
    verdict: { type: 'string', enum: ['Так', 'Ні'] },
    analysis: { type: 'string', description: 'Повний текст виправлень (нумерований список «оригінал» → «виправлення» — правило). Порожньо, якщо verdict = "Ні".' },
  },
};

// Editor / translator return the article in "# Title\n\nbody" (editor) or "Title\n\nbody" (translator)
// markdown in a single field; the workflow parses title/content from it like prod.
const EDITOR_SCHEMA = {
  type: 'object',
  required: ['markdown'],
  properties: {
    markdown: { type: 'string', description: 'Уся виправлена стаття: перший рядок «# Заголовок», потім порожній рядок, далі текст статті у Markdown.' },
  },
};
const TRANSLATE_SCHEMA = {
  type: 'object',
  required: ['markdown'],
  properties: {
    markdown: { type: 'string', description: 'Повний переклад статті українською: перший рядок — заголовок, далі порожній рядок і текст статті у Markdown.' },
  },
};

const A = typeof args === 'string' ? JSON.parse(args) : (args || {});
const MAX_CYCLES = A.maxCycles || 16; // safety cap only; oscillation is intentionally untracked
let title = A.title || '';
let content = A.content || '';
const isScience = A.isScience === true || A.isScience === 1 || A.isScience === 'article' || A.platform === 'article';
const date = A.dateFormatted || A.date || '';
const analyzerModel = A.analyzerModel || 'opus';
const editorModel = A.editorModel || 'sonnet';
const translatorModel = A.translatorModel || 'opus';

// Translation decision: explicit `translate` flag wins; otherwise derive from language + is_translated
// (translate only a non-Ukrainian, not-yet-translated article — mirrors prod's TranslateNewsJob skip).
const lang = String(A.language || '').toLowerCase();
const isTranslated = A.isTranslated === true || A.isTranslated === 1 || A.is_translated === true || A.is_translated === 1;
let needsTranslation;
if (A.translate === true || A.translate === 1) needsTranslation = true;
else if (A.translate === false || A.translate === 0) needsTranslation = false;
else needsTranslation = !!lang && lang !== 'uk' && !isTranslated;

const translatorType = isScience ? 'translation-translator-science' : 'translation-translator';
const analyzerType = isScience ? 'translation-analyzer-science' : 'translation-analyzer';
const editorType = isScience ? 'translation-editor-science' : 'translation-editor';

let outcome = 'capped';
let cyclesRun = 0;
let lastAnalysis = '';
let appliedCycles = 0;
let translated = false;

// ---- Translate to Ukrainian first, if the article is not Ukrainian yet ----
if (needsTranslation) {
  phase('Translate');
  const tr = await agent(
    (date ? '[СЛУЖБОВЕ, не частина статті — НЕ включай у відповідь] Сьогоднішня дата для адаптації часу: ' + date + '\n\n' : '') +
    title + '\n\n' + content +
    '\n\nПереклади цю статтю українською згідно зі своїми інструкціями. Поверни УВЕСЬ переклад у полі `markdown` (перший рядок — заголовок, далі порожній рядок і текст статті у Markdown; без обгорток ```). НЕ додавай дату, службові рядки чи примітки.',
    { agentType: translatorType, schema: TRANSLATE_SCHEMA, model: translatorModel, label: 'translate' }
  );
  // Parse "title\n\nbody" like prod TranslateNewsJob L98-102 (first-newline split, strip #/*, drop **).
  let tmd = (tr.markdown || '').trim().replace(/^```(?:markdown)?\s*\n?/i, '').replace(/\n?```\s*$/i, '').trim();
  const tnl = tmd.indexOf('\n');
  const tTitle = (tnl >= 0 ? tmd.slice(0, tnl) : tmd).replace(/^[#*\s]+/, '').replace(/[#*\s]+$/, '').trim();
  let tContent = (tnl >= 0 ? tmd.slice(tnl + 1) : '').replace(/\*\*/g, '').trim();
  if (tTitle) title = tTitle;
  if (tContent) content = tContent;
  translated = true;
  log('translated → UK (' + translatorType + '): title ' + title.length + ' / content ' + content.length + ' chars');
}

// ---- Analyze ↔ Apply loop (with two-strike «Ні» confirmation) ----
for (let i = 1; i <= MAX_CYCLES; i++) {
  cyclesRun = i;
  const article = '# ' + title + '\n\n' + content;

  phase('Analyze');
  const analyzerMsg =
    (date ? '[СЛУЖБОВЕ, не частина статті] Сьогоднішня дата для аналізу часу за правилом 26: ' + date + '\n\n' : '') +
    article +
    '\n\nПроаналізуй статтю (ігноруй службовий рядок вище) згідно зі своїми інструкціями. Поверни структуровану відповідь:\n' +
    '- verdict: "Так", якщо є хоч одне виправлення; "Ні", якщо текст не потребує змін;\n' +
    '- analysis: повний текст виправлень (нумерований список «оригінал» → «виправлення» — правило). Залиш порожнім, якщо verdict = "Ні".';
  let a = await agent(analyzerMsg, { agentType: analyzerType, schema: ANALYZER_SCHEMA, model: analyzerModel, label: 'analyze #' + i });
  log('cycle ' + i + ': verdict=' + a.verdict + (a.analysis ? ' | corrections ' + a.analysis.length + ' chars' : ''));

  // Two-strike confirmation on "Ні": a single "Ні" is NOT trusted as clean — re-sample the analyzer
  // (fresh call, same text) to be sure no signs of translationese remain. Only TWO consecutive "Ні"
  // end the loop (prod keeps this because a meaningful fraction of a first "Ні" flips to "Так" on an
  // independent second pass). If the confirmation finds corrections, apply them this cycle.
  if (a.verdict === 'Ні' || !a.analysis || !a.analysis.trim()) {
    const confirm = await agent(analyzerMsg, { agentType: analyzerType, schema: ANALYZER_SCHEMA, model: analyzerModel, label: 'confirm #' + i });
    log('cycle ' + i + ': first "Ні" → confirmation verdict=' + confirm.verdict);
    if (confirm.verdict === 'Ні' || !confirm.analysis || !confirm.analysis.trim()) {
      lastAnalysis = 'Ні';
      outcome = 'converged-clean';
      break;
    }
    a = confirm; // confirmation found corrections → apply them this cycle
  }
  lastAnalysis = (a.analysis && a.analysis.trim()) ? a.analysis : a.verdict;

  phase('Apply');
  const ed = await agent(
    (date ? '[СЛУЖБОВЕ, не частина статті — НЕ включай у відповідь] Дата статті: ' + date + '\n\n' : '') +
    article +
    '\n\n---\nВиправлення філолога:\n' + a.analysis +
    '\n\nЗастосуй ці виправлення згідно зі своїми інструкціями. Поверни УВЕСЬ виправлений текст статті у полі `markdown` (формат: «# Заголовок», порожній рядок, далі текст; без обгорток ```). НЕ додавай дату, службові рядки, маркери чи будь-які примітки до тексту.',
    { agentType: editorType, schema: EDITOR_SCHEMA, model: editorModel, label: 'apply #' + i }
  );
  // Parse "# Title\n\nbody" from the editor output, mirroring prod (ApplyNewsAnalysisJob L182-186).
  let md = (ed.markdown || '').trim();
  md = md.replace(/^```(?:markdown)?\s*\n?/i, '').replace(/\n?```\s*$/i, '').trim();
  const nl = md.indexOf('\n');
  const parsedTitle = (nl >= 0 ? md.slice(0, nl) : md).replace(/^[#*\s]+/, '').replace(/[#*\s]+$/, '').trim();
  let parsedContent = (nl >= 0 ? md.slice(nl + 1) : '').trim();
  parsedContent = parsedContent.replace(/\s*(\n\s*---\s*)+\s*$/, '').trim();
  if (parsedTitle) title = parsedTitle;
  if (parsedContent) content = parsedContent;
  appliedCycles++;
}

return { title, content, outcome, cyclesRun, lastAnalysis, appliedCycles, isScience, translated, translatorType, analyzerType, editorType };
